export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const CREATE_NEW_SESSION = 'CREATE_NEW_SESSION';
export const FIND_OPEN_SESSIONS = 'FIND_OPEN_SESSIONS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

